// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class Conference
{
    public int ConferenceId { get; set; }

    public int OrganizerId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<ConferenceMessage> ConferenceMessages { get; set; } = new List<ConferenceMessage>();

    public virtual ICollection<ConferenceParticipant> ConferenceParticipants { get; set; } = new List<ConferenceParticipant>();

    public virtual User Organizer { get; set; }
}