// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class ConferenceMessage
{
    public int MessageId { get; set; }

    public int ConferenceId { get; set; }

    public int SenderId { get; set; }

    public int? ReceiverId { get; set; }

    public string MessageText { get; set; }

    public DateTime SentTime { get; set; }

    public virtual Conference Conference { get; set; }

    public virtual ConferenceParticipant Receiver { get; set; }

    public virtual ConferenceParticipant Sender { get; set; }
}