// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class ConferenceParticipant
{
    public int Id { get; set; }

    public int ConferenceId { get; set; }

    public int? UserId { get; set; }

    public int? GuestId { get; set; }

    public virtual Conference Conference { get; set; }

    public virtual ICollection<ConferenceMessage> ConferenceMessageReceivers { get; set; } = new List<ConferenceMessage>();

    public virtual ICollection<ConferenceMessage> ConferenceMessageSenders { get; set; } = new List<ConferenceMessage>();

    public virtual Guest Guest { get; set; }

    public virtual User User { get; set; }
}