// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class Guest
{
    public int GuestId { get; set; }

    public string GuestName { get; set; }

    public virtual ICollection<ConferenceParticipant> ConferenceParticipants { get; set; } = new List<ConferenceParticipant>();
}