// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Server.Models;

public partial class MeetingsContext : DbContext
{
    public MeetingsContext()
            : base(new DbContextOptionsBuilder<MeetingsContext>()
                   .UseSqlServer("Server=desktop-anh3eij;Database=Meetings;Trusted_Connection=True;TrustServerCertificate=True;")
                   .Options)
    {
    }

    public virtual DbSet<Conference> Conferences { get; set; }

    public virtual DbSet<ConferenceMessage> ConferenceMessages { get; set; }

    public virtual DbSet<ConferenceParticipant> ConferenceParticipants { get; set; }

    public virtual DbSet<Guest> Guests { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Conference>(entity =>
        {
            entity.HasKey(e => e.ConferenceId).HasName("PK__Conferen__E6E19E1F4D6A046B");

            entity.Property(e => e.ConferenceId).HasColumnName("Conference_ID");
            entity.Property(e => e.EndTime)
                .HasColumnType("smalldatetime")
                .HasColumnName("End_time");
            entity.Property(e => e.IsActive).HasColumnName("Is_active");
            entity.Property(e => e.OrganizerId).HasColumnName("Organizer_ID");
            entity.Property(e => e.StartTime)
                .HasColumnType("smalldatetime")
                .HasColumnName("Start_time");

            entity.HasOne(d => d.Organizer).WithMany(p => p.Conferences)
                .HasForeignKey(d => d.OrganizerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Conferenc__Organ__75A278F5");
        });

        modelBuilder.Entity<ConferenceMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Conferen__F5A446E2625BA16E");

            entity.ToTable("Conference_Messages");

            entity.Property(e => e.MessageId).HasColumnName("Message_ID");
            entity.Property(e => e.ConferenceId).HasColumnName("Conference_ID");
            entity.Property(e => e.MessageText)
                .IsRequired()
                .HasColumnName("Message_text");
            entity.Property(e => e.ReceiverId).HasColumnName("Receiver_ID");
            entity.Property(e => e.SenderId).HasColumnName("Sender_ID");
            entity.Property(e => e.SentTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Sent_time");

            entity.HasOne(d => d.Conference).WithMany(p => p.ConferenceMessages)
                .HasForeignKey(d => d.ConferenceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Conferenc__Sent___00200768");

            entity.HasOne(d => d.Receiver).WithMany(p => p.ConferenceMessageReceivers)
                .HasForeignKey(d => d.ReceiverId)
                .HasConstraintName("FK__Conferenc__Recei__02084FDA");

            entity.HasOne(d => d.Sender).WithMany(p => p.ConferenceMessageSenders)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Conferenc__Sende__01142BA1");
        });

        modelBuilder.Entity<ConferenceParticipant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Conferen__3214EC27BD14B612");

            entity.ToTable("Conference_Participants");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ConferenceId).HasColumnName("Conference_ID");
            entity.Property(e => e.GuestId).HasColumnName("Guest_ID");
            entity.Property(e => e.UserId).HasColumnName("User_ID");

            entity.HasOne(d => d.Conference).WithMany(p => p.ConferenceParticipants)
                .HasForeignKey(d => d.ConferenceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Conferenc__Confe__7A672E12");

            entity.HasOne(d => d.Guest).WithMany(p => p.ConferenceParticipants)
                .HasForeignKey(d => d.GuestId)
                .HasConstraintName("FK__Conferenc__Guest__7C4F7684");

            entity.HasOne(d => d.User).WithMany(p => p.ConferenceParticipants)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Conferenc__User___7B5B524B");
        });

        modelBuilder.Entity<Guest>(entity =>
        {
            entity.HasKey(e => e.GuestId).HasName("PK__Guests__CB8B0D5329B689FE");

            entity.Property(e => e.GuestId).HasColumnName("Guest_ID");
            entity.Property(e => e.GuestName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Guest_name");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__206D9190461A2CD6");

            entity.Property(e => e.UserId).HasColumnName("User_ID");
            entity.Property(e => e.UserLogin)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("User_login");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("User_name");
            entity.Property(e => e.UserPassword)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("User_password");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}