// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserLogin { get; set; }

    public string UserPassword { get; set; }

    public string UserName { get; set; }

    public virtual ICollection<ConferenceParticipant> ConferenceParticipants { get; set; } = new List<ConferenceParticipant>();

    public virtual ICollection<Conference> Conferences { get; set; } = new List<Conference>();
}